### ISSUE TITLE
Just some info to add

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#1]
Details About Event (Some of these may change in the future)
Where: Kennett High School
Kennett Square, PA
Starts - 02/26/2016 @ 10:00 pm
Ends  -  02/27/2016 @ 6:00 am
Check-in Time: 9:00 pm to 10:45 pm
Registration Cutoff : 02/11/2016 11:45 pm

Registration info (How to register):
This can be implemented any way you choose.

Go to http://fourdiamonds.donordrive.com/event/khs16
Click "Register Now!"
Select "Participant"
Click Continue
Type in fundraising goal (Minimum is $50.00)
Select Grade
Select T-Shirt Size
Click Continue
Fill in all required information
Click Continue
Choose weather to make a donation now or later
Click Continue
Review your registration information
Click Complete Registration

**Comment by Ernie3** [comment]
Maybe we can just in bed this: 

https://docs.google.com/presentation/d/1RfTcfq40UAc3QXaqVh9vkIDQ4Jn2SwgpyAOVnDyCWUM/pub?start=false&loop=false&delayms=3000&slide=id.p

using reveal.js? Not sure, what do you think @JoseRoman?

**Comment by theseanconn** [comment]
Just a side note:
This registration part that you are talking about adding is the online registration only.
We will eventually have a "Dancer Packet" that will include medical forms and other important forms that will be a physical packet of paper.
This could also be included on the website as a downloadable PDF or something. Ill let you know when we finish it.

**Comment by JoseRoman** [comment]
@theseanconn, @Ernie3: I'm working on the 'How to Sign Up' section. Will we need to add "Sign Up" to the navegation bar? 
![image](https://cloud.githubusercontent.com/assets/4240075/10407897/46f8f150-6ea6-11e5-8110-8dd965817a00.png)

**Comment by Ernie3** [comment]
Yeah that's a good idea. Just before contact maybe?

On Friday, October 9, 2015, Jose Roman <notifications@github.com> wrote:

> @theseanconn <https://github.com/theseanconn>, @Ernie3
> <https://github.com/Ernie3>: I'm working on the 'How to Sign Up' section.
> Will we need to add "Sign Up" to the navegation bar?
> [image: image]
> <https://cloud.githubusercontent.com/assets/4240075/10407897/46f8f150-6ea6-11e5-8110-8dd965817a00.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/1#issuecomment-147013332>.
>


-- 

Thank you,

Ernest G. Wilson III
Email: ErnestGWilsonIII@gmail.com
Cell: 302.668.7620

**Comment by JoseRoman** [comment]
@Ernie3: Yeah, I think that would be a good place to put it. :+1:

**Comment by JoseRoman** [comment]
@Ernie3, @theseanconn: I added the steps to sign up. The style is different in mobile and tablets than in desktops. Let me know if I have to change anything.

![image](https://cloud.githubusercontent.com/assets/4240075/10409381/3a6ea254-6ed3-11e5-934b-d570c514324a.png)

 
![image](https://cloud.githubusercontent.com/assets/4240075/10409386/5325b6de-6ed3-11e5-81d5-0cfbb76fcc03.png)

**Comment by JoseRoman** [comment]
@Ernie3, @theseanconn: Can this issue be closed?

**Comment by Ernie3** [comment]
We're good here
