### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#11]
Will http://khs-minithon.github.io/website/ be our permanent address? 
I am asking because we are going to make a QR code that leads to the website. We plan to give copies of this QR code to every 8th period teacher to hand out to kids when they get back in from the pep rally.

**Comment by Ernie3** [comment]
That will not. That address is only for development (while we are working on it)

**Comment by theseanconn** [comment]
ok

**Comment by theseanconn** [comment]
Do you have a time frame on when you think we can get a permanent address?
Have you talked to your dad about us possibly being hosted for free?
