### ISSUE TITLE
Comments from our contact at Four Diamonds

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#13]
Okay, so I emailed our contact at Four Diamonds and gave him the development link and asked him to review it and let us know if anything violates the acceptable logo/images/reference use. Here is what he said: ***Just a note: He said "Mike might have more"... "Mike" is his co-worker at Four Diamonds and I CCd him in the email.***

Hi Sean,
 
First off – this is an awesome website. Easily one of the best that I’ve seen a Mini-THON do, especially for a first year school.
 
Just a few edits (Mike might have more):
Who Are We Are? – do you need the second “Are?” and I recommend using the word “childhood” instead of “pediatric”
What We Do – take out the word “Fund.” We now refer to ourselves as just “Four Diamonds”
Research – have it start as, “Through Four Diamonds, Penn State Hershey….”
 
If you don’t mind adding the Four Diamonds and/or Mini-THON logo under “Our Partners” that would be great.
 
Awesome job!
 
Kinjal

**Comment by Ernie3** [comment]
Cool. I will make those edits in thee email when I get a chance.

On Friday, October 2, 2015, Sean Connolly <notifications@github.com> wrote:

> Okay, so I emailed our contact at Four Diamonds and gave him the
> development link and asked him to review it and let us know if anything
> violates the acceptable logo/images/reference use. Here is what he said: *Just
> a note: He said "Mike might have more"... "Mike" is his co-worker at Four
> Diamonds and I CCd him in the email.*
>
> Hi Sean,
>
> First off – this is an awesome website. Easily one of the best that I’ve
> seen a Mini-THON do, especially for a first year school.
>
> Just a few edits (Mike might have more):
> Who Are We Are? – do you need the second “Are?” and I recommend using the
> word “childhood” instead of “pediatric”
> What We Do – take out the word “Fund.” We now refer to ourselves as just
> “Four Diamonds”
> Research – have it start as, “Through Four Diamonds, Penn State Hershey….”
>
> If you don’t mind adding the Four Diamonds and/or Mini-THON logo under
> “Our Partners” that would be great.
>
> Awesome job!
>
> Kinjal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/13>.
>


-- 

Thank you,

Ernest G. Wilson III
Email: ErnestGWilsonIII@gmail.com
Cell: 302.668.7620

**Comment by JoseRoman** [comment]
made the changes...still need to add the logo to "Our Partnes" section

**Comment by theseanconn** [comment]
When you get a chance can we push those changes to the gh-pages branch so the development link will be updated.

**Comment by JoseRoman** [comment]
@theseanconn how many sponsor logos are we expecting? because if there are going to be more I will leave the website how it is in the picture below 
![image](https://cloud.githubusercontent.com/assets/4240075/10258638/b7eec67e-6914-11e5-9478-f8456170e9a2.png)

but if there are only 2 it is more eye friendly to have them both in the center

**Comment by theseanconn** [comment]
We should center those for now and if we have more later we can change the arrangement.
