### ISSUE TITLE
List of members (name and pictures)

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#15]
we might also need order

**Comment by Ernie3** [comment]
Just to add, the pictures should really only be a head shots

**Comment by theseanconn** [comment]
The will be headshots.
I figure that each picture should include the committee email address under it or something so I am going to reinclude the emails in this. Each committee picture should probably (maybe) include the names of the people too.
The order goes as follows (starting from top left to right):
Overall  (khsminithon@gmail.com) - Sean Connolly & Austin Maxwell
Finance (khsminithon.finance@gmail.com) - Casey Bruno & Ben Skross
Community Outreach  (khsminithon.communityoutreach@gmail.com) - Hannah Wissner & Samantha Weaver
Operations (khsminithon.operations@gmail.com) - Olivia Pagliaro & Molly Adelman
Hospitality (khsminithon.hospitality@gmail.com) - Sarah Stephens & Gemma Erickson
Entertainment (khsminithon.entertainment@gmail.com) - Noah Hall & Maddy Dungey & Delaney Baird
Special Events (khsminithon.specialevents@gmail.com) - Ariana Meola & Julia Sharp
Social Media/Tech (Ernie if you want to include your own picture you can split this one into two) (khsminithon.socialmedia.tech@gmail.com) - Imogen Thomas & Kelsey Mentzer & Ernie Wilson

**Comment by Magnus-Murray** [comment]
HEY HI GUYS HEY HEY
Date: Thu, 8 Oct 2015 15:12:28 -0700

**Comment by theseanconn** [comment]
@Ernie3 
I was thinking it would be one picture for each committee... So each picture would include all of that committee's chairs.
So like there would be one picture for Overall and it would have Austin and myself in the picture.
The Finance picture would have Ben and Casey.

Get what im saying?

**Comment by Ernie3** [comment]
Okay I get what you're saying, when I get a chance I will look into that

**Comment by JoseRoman** [comment]
@theseanconn: @Ernie3 added the members to http://khs-minithon.github.io/website/#team-section. Keep in mind that is not the final version and we will make it so that each diamond is a different comittee.

**Comment by theseanconn** [comment]
Can we change the first diamond from "Overseers" to "Overall"

**Comment by JoseRoman** [comment]
@theseanconn done

**Comment by JoseRoman** [comment]
@theseanconn any updates for the pictures?

**Comment by theseanconn** [comment]
Pictures coming soon.
Ill make a new thread with them as they come in.

**Comment by theseanconn** [comment]
Can we close this?
