### ISSUE TITLE
Add newsletter subscribe functionality

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#17]

**Comment by Ernie3** [comment]
Still debating on whether or not to add this functionality given that if someone wants to unsubscribe, they may think to come to us and not Four Diamonds. What are our current thoughts on this @JoseRoman?

**Comment by JoseRoman** [comment]
@Ernie3, @theseanconn: Although we might not be able to allow users to sign up for the newsletter of Four Diamonds, it is possible to create a separate newsletter for KHS only which the committee can be in charge of. 

If the option to subscribe to the Four Diamonds newsletter is a must, I will need to talk to whoever is in charge of the web development/technology so that Ernie and I can coordinate and make the necessary adjustments.

**Comment by theseanconn** [comment]
Subscribing to the Four Diamonds Newsletter is not a must. Austin and I will assign it to a committee and KHS will have our own News letter.

**Comment by Ernie3** [comment]
Perfect then, we can add a subscribe button to our own newsletter. Sound good @theseanconn?

**Comment by JoseRoman** [comment]
@Ernie3, @theseanconn: This needs more information, are you guys going to use MailChimp or a similar service?

**Comment by theseanconn** [comment]
What do you suggest?

On Tue, Oct 20, 2015 at 4:50 PM, Jose Roman <notifications@github.com>
wrote:

> @Ernie3 <https://github.com/Ernie3>, @theseanconn
> <https://github.com/theseanconn>: This needs more information, are you
> guys going to use MailChimp or a similar service?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/17#issuecomment-149697939>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

Event Page <http://fourdiamonds.donordrive.com/event/khs16>    Twitter
<http://twitter.com/khsminithon>  Instagram
<http://instagram.com/khsminithon>

**Comment by JoseRoman** [comment]
@theseanconn MailChimp is great. Their free plan offer up to 2,000 subscribers and 12,000 emails per month.

**Comment by theseanconn** [comment]
Okay, ill look into it.

On Tue, Oct 20, 2015 at 5:51 PM, Jose Roman <notifications@github.com>
wrote:

> @theseanconn <https://github.com/theseanconn> MailChimp is great. Their
> free plan offer up to 2,000 subscribers and 12,000 emails per month.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/17#issuecomment-149713647>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

Event Page <http://fourdiamonds.donordrive.com/event/khs16>    Twitter
<http://twitter.com/khsminithon>  Instagram
<http://instagram.com/khsminithon>

**Comment by theseanconn** [comment]
Actually I dont know if we are going to do this. I think at this point it is too much for the committees to handle. This is only our first year doing this and we are already spread thin.

**Comment by JoseRoman** [comment]
@theseanconn: so can we close this issue then?

**Comment by Ernie3** [comment]
We will remove it for now. In the future if this needs to be added then let us know by creating a ticket with details. We'd like to push this project into production within this month, so let's start handling the tickets we know HAVE to get done
