### ISSUE TITLE
Website Testing

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#19]
As @Ernie3 and I are making changes to the website, there might be things that get affected and we don't notice. I recommend that members of the club start accessing the temporary [page](http://khs-minithon.github.io/website/) from phones, tablets, or any other device with access to the internet. This is so that we can get any suggestions or fix any bugs that people might find. 

@theseanconn @Magnus-Murray

**Comment by theseanconn** [comment]
Okay, ill send an email out in the morning with the link

**Comment by JoseRoman** [comment]
@theseanconn Thanks.

**Comment by JoseRoman** [comment]
@theseanconn I forgot to mention, make sure that they provide as much details as possible (Android or iPhone, OS, screenshots, ect)

**Comment by theseanconn** [comment]
I sent the email. Ill let you know of any issues/bugs. @JoseRoman

**Comment by Ernie3** [comment]
Sometime early this week (tomorrow or Tuesday) when a lot final/major changes get done it would be nice for another mass email to the members to checkout out the page and report final bugs. So that they do, I would mention to go to it ASAP, scroll thru a bit and report ANY bugs along with the device and browser type/version. It's imperative we get rid of the stupid stuff before rolling out to prod. But again not until a lot of important tickets that are open get done (make sure to emphasize that so people actually do visit and say something)
/cc @theseanconn

**Comment by theseanconn** [comment]
Ok I'll send it out tonight.

On Sunday, October 25, 2015, Ernie Wilson <notifications@github.com> wrote:

> Sometime early this week (tomorrow or Tuesday) when a lot final/major
> changes get done it would be nice for another mass email to the members to
> checkout out the page and report final bugs. So that they do, I would
> mention to go to it ASAP, scroll thru a bit and report ANY bugs along with
> the device and browser type/version. It's imperative we get rid of the
> stupid stuff before rolling out to prod. But again not until a lot of
> important tickets that are open get done (make sure to emphasize that so
> people actually do visit and say something)
> /cc @theseanconn <https://github.com/theseanconn>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/19#issuecomment-150989551>
> .
>


-- 
~Sean

**Comment by Ernie3** [comment]
Not until a bit later

**Comment by theseanconn** [comment]
Okay ill send it out tuesday then.

On Sun, Oct 25, 2015 at 8:27 PM, Ernie Wilson <notifications@github.com>
wrote:

> Not until a bit later
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/19#issuecomment-150991560>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

Event Page <http://fourdiamonds.donordrive.com/event/khs16>    Twitter
<http://twitter.com/khsminithon>  Instagram
<http://instagram.com/khsminithon>
