### ISSUE TITLE
Map photo at Contact Page is a bit funky with some devices

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#2]
On my netbook, for example, the map does not parallax properly. The bottom of the map is cut off leaving a gross black bar. But on my desktop, it looks fine. We should look into fitting the picture given the user's screen size/device.

![contact-bug](https://cloud.githubusercontent.com/assets/6378488/10009783/d667be16-60af-11e5-9983-670ee1c73eb8.PNG)

**Comment by Ernie3** [comment]
Too blurry and not worth time right now, if we want to add this in the future we can but it isn't a priority right now. Taken down for now
