### ISSUE TITLE
Home page photo does not parallax properly

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#21]
![capture](https://cloud.githubusercontent.com/assets/6378488/10419620/c24dda0a-704a-11e5-859b-9eb803371acb.PNG)

This no look pretty :P

**Comment by Ernie3** [comment]
Disregard that streak in the middle left, snipping tool kept crashing and I guess I accidentally wrote on it as it was unresponsive

**Comment by theseanconn** [comment]
Just a side note.
This picture will probably change in the near future whenever we have a logo made.

**Comment by Ernie3** [comment]
What's odd enough is it's working properly now...... Interesting

**Comment by JoseRoman** [comment]
@Ernie3 I cannot reproduce this problem. Up to you whether to close or not.

**Comment by JoseRoman** [comment]
@Ernie3 Can this be closed?

**Comment by Ernie3** [comment]
I suppose
