### ISSUE TITLE
Move two of the diamonds

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#22]
Move the "Social Media" and the "Technology" member diamonds underneath the others to make it cleaner.

So the diamonds should look like an upside down pyramid so it goes from top to bottom:
4 diamonds
3 diamonds
2 diamonds.

**Comment by JoseRoman** [comment]
@theseanconn: Please close this issue if everything is fine with the diamonds order. https://github.com/KHS-Minithon/website/commit/eea3cf0d664d2b68c590d4cdf3e25ccd091028d7

**Comment by theseanconn** [comment]
Its not pushed. I cant view it. @JoseRoman

**Comment by JoseRoman** [comment]
@theseanconn: It is pushed on both branches. Make sure you clear your cache (Ctrl + F5 while on the page)
