### ISSUE TITLE
Countdown Timer Thing

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#23]
Would it be possible to add a countdown timer thing saying how many days, hours, and minutes (and maybe seconds) there is until our Mini-THON.
The Mini-THON starts February 26th, 2016 at 10:00pm

**Comment by JoseRoman** [comment]
@theseanconn where would you want this?

**Comment by theseanconn** [comment]
Probably in that top blue area... top left or something. @JoseRoman

**Comment by JoseRoman** [comment]
@theseanconn, @Ernie3: putting the countdown timer on the menu might cause problems in some phones...how about between the title and the subtext? 
![image](https://cloud.githubusercontent.com/assets/4240075/10526752/84691a98-7341-11e5-8e5c-8906dc1dd59b.png)

**Comment by theseanconn** [comment]
It would definataly look nicer up in the top blue area but I guess that works fine... or even between the subtext and the signup button. @JoseRoman

**Comment by Ernie3** [comment]
yoink

**Comment by Ernie3** [comment]
I added one, but it does not compensate for different days in each month. We will have to implement that. Passes to Jose

**Comment by Ernie3** [comment]
On another note, there is so much going on for mobile that the Sign up is now off the screen on the home page. Might want to look into that as well. Maybe smaller font (for mobile)?
/cc @JoseRoman

**Comment by Ernie3** [comment]
Hey @JoseRoman I added one that uses vanilla JS, but if we want something quick and nifty: 
https://github.com/hilios/jQuery.countdown

We don't have to, just a thought

**Comment by Ernie3** [comment]
I made a few tweaks. This is good enough for now (at least I think). Later we can adjust the margins but this shouldn't stop us from putting it to prod this week. Going to make a separate ticket on this that's fresh.
