### ISSUE TITLE
Website Hosting - *PLEASE DO NOT CLOSE*

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#26]
I know we know about this and I know it is being worked on. I just want to have an open ticket as a reminder.

The website needs to be hosted and have a permanent URL (khsminithon.org (or .com not sure what you think)) before October 30th, 2015.
We plan to print out QR codes that link to the URL to hand out during the pep rally.

**Comment by Ernie3** [comment]
This will most definitely be a .org. And I am thinking "khsminithon.org" will be the URL.

**Comment by JoseRoman** [comment]
The domain name will be khsminithon.org (shout-out to @Ernie3 for the donation :+1: #Respect)

**Comment by Ernie3** [comment]
Domain Name "khsminithon.org" has been reserved

**Comment by theseanconn** [comment]
Lets keep this open until the site officially goes live.

**Comment by theseanconn** [comment]
We are done with this I think.
