### ISSUE TITLE
Contact Section Emails

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#29]
Closed the old thread #6 and am making this new one just to clean it up a bit and with updated information:

They are as follows:

khsminithon@gmail.com ---- Overall

khsminithon.finance@gmail.com --- Finance

khsminithon.communityoutreach@gmail.com --- Community Outreach

khsminithon.specialevents@gmail.com ---- Special Events

khsminithon.hospitality@gmail.com --- Hospitality

khsminithon.operations@gmail.com --- Operations

khsminithon.entertainment@gmail.com ---- Entertainment

khsminithon.socialmedia@gmail.com --- Social Media

khsminithon.tech@gmail.com --- Technology

**Comment by JoseRoman** [comment]
https://github.com/KHS-Minithon/website/commit/05639937805bb8979c71d7f40a588dfb16d996e3
