### ISSUE TITLE
Meet The Families

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#3]
Maybe embed these

http://www.fourdiamonds.org/about-us/#about-usmeet-our-families

**Comment by Ernie3** [comment]
We can probably embed these under the "Our Works" section and just have the video boxes inline with the photo boxes

**Comment by JoseRoman** [comment]
@Ernie3, @theseanconn: I added the videos to the website.

**Comment by Ernie3** [comment]
Looks good to me

**Comment by theseanconn** [comment]
Looks good.
