### ISSUE TITLE
Fix Dimmed Contact Header

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#32]
I am sure this will take two seconds, but it is late and I am mentally drained.

![capture](https://cloud.githubusercontent.com/assets/6378488/10709167/1e9cd956-79f0-11e5-926b-2964b48d4b41.PNG)

**Comment by Ernie3** [comment]
@JoseRoman can you knock this out by this evening real quick?

**Comment by theseanconn** [comment]
We dont need this anymore do we?
