### ISSUE TITLE
Make Countdown Timer More Accurate

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#35]
For now, the timer is on point to 02/26/16 at 9PM. However, it does not take into account varying number of days in months (workaround at the moment is adding 1 to number of months, since all months from now to Feb have 31 days except November). This is something that can be fixed after being pushed to prod, however, so not a giant deal, seeming how it is accurate for the moment, but possibly not for the future on new Mini-THON dates.

**Comment by theseanconn** [comment]
Just a thought. Im looking around and there are tons of sites to make a HTML embeddable timer... here is an example:
http://itsalmo.st/#timeforthekhsmini-thon
http://www.timeanddate.com/clocks/freecountdown.html

I figure using one of these will be more accurate. Just an idea though.

**Comment by theseanconn** [comment]
This would be kind of what I want and it is accurate too.

<iframe src="http://free.timeanddate.com/countdown/i4wt9oud/n179/cf12/cm0/cu4/ct0/cs0/ca0/cr0/ss0/cac000/cpc000/pcfff/tcfff/fn3/fs100/szw448/szh189/tatThe%20KHS%20Mini-THON%20Begins%20in/tac000/tptTime%20Since%20Mini-THON%20Start/tpc000/mat%20/mac000/mpt%20%20/mpc000/iso2016-02-26T22:00:00" allowTransparency="true" frameborder="0" width="359" height="62"></iframe>

**Comment by theseanconn** [comment]
And actually on that note, can we make the timer's largest value be days. So remove the months.

**Comment by Ernie3** [comment]
You want it to be "days hours minutes seconds"?

**Comment by theseanconn** [comment]
Correct.

On Tue, Oct 27, 2015 at 6:30 PM, Ernie Wilson <notifications@github.com>
wrote:

> You want it to be "days hours minutes seconds"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/35#issuecomment-151664341>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

*Website <http://khsminithon.org>*
Event Page <http://fourdiamonds.donordrive.com/event/khs16>
Twitter  <http://twitter.com/khsminithon>
Instagram <http://instagram.com/khsminithon>

**Comment by Ernie3** [comment]
Done, will update site shortly

**Comment by theseanconn** [comment]
In addition, you have the timer set to 9:00pm... it should be set to 10:00pm. Checkin starts at 9:00pm but the actual mini-THON starts at 10:00pm. @Ernie3

**Comment by Ernie3** [comment]
Keep in mind @theseanconn it will always be accurate now, and no need to add dependencies mentioned above

**Comment by theseanconn** [comment]
Okay @Ernie3
