### ISSUE TITLE
Money Raised

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#39]
I know we already have something in place for this but I just had a correction/issue/thought.

The money raised bar on the website is only pulling it from DonorDrive. DonorDrive is not the only place we are raising money however.
Our actual total raised money can be found here:
https://docs.google.com/spreadsheets/d/1PE1umwfQwSwaNxX_Hishe8kKmcNPRQmRBv-GrPrBFDw/edit?usp=sharing

I dont know if there is any way that we can make that total the total on the website.
Any ideas?

@JoseRoman @Ernie3

**Comment by JoseRoman** [comment]
@theseanconn: You tell us this one day before we have to deploy the website?

**Comment by theseanconn** [comment]
@JoseRoman Yeah sorry, just thought about it.
It doesnt have to be done right away. Can we just start thinking about how to maybe implement this if possible?

**Comment by Ernie3** [comment]
Don't worry about it @theseanconn 

@JoseRoman Looking into how to retrieve a Google Spreadsheet as a JSON, haven't tried it but came across this: https://coderwall.com/p/duapqq/use-a-google-spreadsheet-as-your-json-backend

**Comment by Ernie3** [comment]
Even more helpful is this: http://www.nextofwindows.com/how-to-use-google-doc-spreadsheet-serve-json-from-excel-spreadsheet/

**Comment by Ernie3** [comment]
We can pull the JSON thru the web instead of a local file, I suggest we try this by following the steps from nextofwindows link above

**Comment by Ernie3** [comment]
Note that we can set the JSON to change every time the spreadsheet is changed. I think this is looking good and we can get this feature rolling for tomorrow. The functionality of the website doesn't have to change, and best of all: NO CRON JOB!! Don't worry @theseanconn if this works it will be better than what we have now :+1:

**Comment by Ernie3** [comment]
Creating a new ticket for this
