### ISSUE TITLE
Change how the total money raised is retrieved

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#40]
We need to pull the data from a Google Spreadsheet (https://docs.google.com/spreadsheets/d/1PE1umwfQwSwaNxX_Hishe8kKmcNPRQmRBv-GrPrBFDw/edit?usp=sharing). I suggest we follow steps from this site: http://www.nextofwindows.com/how-to-use-google-doc-spreadsheet-serve-json-from-excel-spreadsheet/ and retrieve the JSON there instead of locally. This removed then need for a cron job as well.

**Comment by Ernie3** [comment]
@theseanconn please let us know when you do this and post the link

**Comment by theseanconn** [comment]
https://docs.google.com/spreadsheets/d/1PE1umwfQwSwaNxX_Hishe8kKmcNPRQmRBv-GrPrBFDw/pubhtml
Im not sure if this is all you need.
The cell that contains the total amount is 36B.

Let me know if you need anything else.

**Comment by Ernie3** [comment]
Not exactly, I need you to go to push to web again, but this time look for a URL under "Get a link to published data"... paste that in here please

**Comment by theseanconn** [comment]
I do not see it.
There is no "Get link to published data"

**Comment by Ernie3** [comment]
When you click publish to the web, what do you see (can you post a screen shot)? The instructions might be outdated

**Comment by JoseRoman** [comment]
File > Publish to the web

**Comment by JoseRoman** [comment]
![image](https://cloud.githubusercontent.com/assets/4240075/10770103/b7c288a2-7ca6-11e5-966e-64c52cccafc2.png)

**Comment by Ernie3** [comment]
@JoseRoman I am trying to get a key from some URL parameter so that I may plug it into another URL as a route so that the spreadsheet comes back as JSON.

**Comment by Ernie3** [comment]
Maybe it is outdated? : https://developers.google.com/gdata/samples/spreadsheet_sample

**Comment by Ernie3** [comment]
https://developers.google.com/gdata/docs/json

"Note: The Google Data client libraries don't currently support JSON."

**Comment by Ernie3** [comment]
Here is the alternative, not a fan but I would work. We can keep the cron job and just pull down the data from the html from https://docs.google.com/spreadsheets/d/1PE1umwfQwSwaNxX_Hishe8kKmcNPRQmRBv-GrPrBFDw/pubhtml

I would like to get JSON working, but that is end all be all

**Comment by JoseRoman** [comment]
@theseanconn Please change the settings or give me permissions to edit (jose.roman32@gmail.com) I was able to create what we needed using a test spreadsheet https://spreadsheets.google.com/feeds/list/1qqPgS9Bi0yAVdVaj47CjlBOZkEOBdHN-BpEX48N3sP4/od6/public/basic?alt=json

**Comment by theseanconn** [comment]
I shared it. @JoseRoman

**Comment by JoseRoman** [comment]
@theseanconn go to the file and click the chat icon

**Comment by theseanconn** [comment]
I think I would have to make you owner for that...
Give me a sec.

**Comment by JoseRoman** [comment]
@Ernie3 close this Sh!t

**Comment by Ernie3** [comment]
Looks good, can you please remove php?

**Comment by theseanconn** [comment]
Can we push this change to khsminithon.org? @Ernie3

**Comment by Ernie3** [comment]
It'll make its way there, @JoseRoman is on it

**Comment by theseanconn** [comment]
Okay.

On Tue, Oct 27, 2015 at 10:01 PM, Ernie Wilson <notifications@github.com>
wrote:

> It'll make its way there, @JoseRoman <https://github.com/JoseRoman> is on
> it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/40#issuecomment-151696819>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

*Website <http://khsminithon.org>*
Event Page <http://fourdiamonds.donordrive.com/event/khs16>
Twitter  <http://twitter.com/khsminithon>
Instagram <http://instagram.com/khsminithon>

**Comment by JoseRoman** [comment]
Working on it

**Comment by Ernie3** [comment]
@theseanconn just an FYI, if we haven't told you, don't move the cell which contains the total raised, otherwise the donation bar won't work
