### ISSUE TITLE
Contact Section

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#41]
I noticed that you removed the entire contact section.

If we could find someplace to include KHS's address and the phone number: 610-444-6617 that would be great.
Thanks!

**Comment by theseanconn** [comment]
Maybe at the very bottom under the "Four Diamonds Links" section we could include a "Kennett High School Info" section or something.

**Comment by Ernie3** [comment]
Can do

**Comment by theseanconn** [comment]
And the email address too. Like the old contact section sort of. khsminithon@gmail.com

**Comment by Ernie3** [comment]
Done
