### ISSUE TITLE
Add Committee Chair Pictures

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#42]
As they come in (either taken by @Ernie3 or sent into khsminithon.tech@gmail.com) they should be uploaded to this thread. After that they can be added to the website in their respective "Our Team" diamond.
@Ernie3 I believe you have "Overall"'s (myself and Austin).

Im not sure if this will be done by the pep rally but we can try and get as many as we can.

**Comment by Ernie3** [comment]
If possible, send out an email tonight saying to go to the library for photos tomorrow before and during advisory. Up to you, but there's no need for Texara or anything since we are just going to the library for a few photos. Your call

**Comment by theseanconn** [comment]
Will you be in the library during advisory? @Ernie3 I can send the email to just the committee chairs.

**Comment by Ernie3** [comment]
Tes

**Comment by theseanconn** [comment]
![image](https://cloud.githubusercontent.com/assets/14626073/10775126/74dbb992-7cdc-11e5-98eb-d33ec7a9aaba.jpeg)
Dont know why its upside down.
@Ernie3 will this picture fit do you think?

Its the Hospitality one.

**Comment by Ernie3** [comment]
Got it

**Comment by Ernie3** [comment]
For now we will add then to img folder and create a separate ticket on implementing them

**Comment by Ernie3** [comment]
@JoseRoman when we get the photos, we will need your photo editing skills to make sure all are equal, look good etc

**Comment by Ernie3** [comment]
Only have half of them, and no emails from anybody nor did people show up at the library... Nice

**Comment by JoseRoman** [comment]
@Ernie3 look them up on social networks and pick their ugliest picture :imp:

**Comment by theseanconn** [comment]
I'm gonna send them one more email in a day or so and basically give them a
deadline for the picture (and some other stuff they NEED to do that they
haven't yet) and say that if they don't have it done by a certain date they
will be replaced.

On Thursday, October 29, 2015, Jose Roman <notifications@github.com> wrote:

> @Ernie3 <https://github.com/Ernie3> look them up on social networks and
> pick their ugliest picture [image: :imp:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/42#issuecomment-152374804>
> .
>


-- 
~Sean

**Comment by theseanconn** [comment]
@Ernie3 Noah Hall (Entertainment) came up to me today and asked about the picture. I just told him to take it with the other chairs when he has time and send it to me or whatever. Should be getting that soon hopefully.

**Comment by theseanconn** [comment]
What are the other committee pictures we still need? @Ernie3

**Comment by Ernie3** [comment]
Whatever isn't on the site I do not have. We will do this on a rolling basis, let me know @theseanconn if you get any photos
