### ISSUE TITLE
Implement Team Photos

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#43]
Basically, we want each diamond to be clickable to the photo (like the "Impact" section) and have the email in the photo as well. At the same time we want to keep hover functionality and font-awesome icon.

**Comment by Ernie3** [comment]
Depends on #42

**Comment by Ernie3** [comment]
@theseanconn So we think we should also add a "role" description for each committee. Can you provide us brief descriptions of each committee so we can add them to team section? 2-5 sentences will suffice.

**Comment by theseanconn** [comment]
Okay, I can do that. Ill add them to this ticket tomorrow.

On Tue, Oct 27, 2015 at 11:07 PM, Ernie Wilson <notifications@github.com>
wrote:

> @theseanconn <https://github.com/theseanconn> So we think we should also
> add a "role" description for each committee. Can you provide us brief
> descriptions of each committee so we can add them to team section? 2-5
> sentences will suffice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/43#issuecomment-151707944>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

*Website <http://khsminithon.org>*
Event Page <http://fourdiamonds.donordrive.com/event/khs16>
Twitter  <http://twitter.com/khsminithon>
Instagram <http://instagram.com/khsminithon>

**Comment by Ernie3** [comment]
Please do so promptly. This is the last thing for prod and we want this up tomorrow!

**Comment by Ernie3** [comment]
Took out section for now for prod URL. We will work on this in dev first

**Comment by Ernie3** [comment]
We will just do this on a rolling basis, @theseanconn let me know when you get photo(s) or whatever
