### ISSUE TITLE
Center Menu Bar?

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#44]
What would you guys think of centering the menu at the top for now? Given we have 8 buttons. We can always move it back when we get a logo. Not sure on the status of that.

@JoseRoman 
@theseanconn

**Comment by theseanconn** [comment]
Go for it.

On Wed, Oct 28, 2015 at 9:27 PM, Ernie Wilson <notifications@github.com>
wrote:

> What would you guys think of centering the menu at the top for now? Given
> we have 8 buttons. We can always move it back when we get a logo. Not sure
> on the status of that.
>
> @JoseRoman <https://github.com/JoseRoman>
> @theseanconn <https://github.com/theseanconn>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/44>.
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

*Website <http://khsminithon.org>*
Event Page <http://fourdiamonds.donordrive.com/event/khs16>
Twitter  <http://twitter.com/khsminithon>
Instagram <http://instagram.com/khsminithon>

**Comment by JoseRoman** [comment]
What kind of logo do you guys want?

**Comment by theseanconn** [comment]
The logo will be added when it is finished. We have people working on it here. We can figure out where to implement it when it is completed. Go ahead and center the menu @JoseRoman @Ernie3
