### ISSUE TITLE
Pep Rally Tomorrow

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#46]
Everything is looking nice. Just wish we had more team photos. Other than that, I think everything is great. Even after announcing tomorrow at the Pep Rally, we can apply changes and add stuff whenever.

@theseanconn What is the status on the cards with the website bar code? Are we handing those out? Also, who is speaking tomorrow? If we need speaker(s) I am willing (not afraid to talk to large crowds).

**Comment by theseanconn** [comment]
Answering in order:
We have printed out ~ 1,200 individual QR code "index" cards to give to the 8th period teachers to give out to students when they arrive back from the pep rally. We have also printed out 90 flyers for teachers to hang in their rooms and also around the school.

I am not sure who is speaking tomorrow but we do have 2 speakers already and there is a script written. I appreciate your willingness to do it.

@Ernie3
