### ISSUE TITLE
Sign up Info

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/website#48]
I hear we are going to have document(s)/PDF(s) and other sign up instructions. @theseanconn please add any information we need to add for sign up info in this ticket

**Comment by theseanconn** [comment]
I will

**Comment by Ernie3** [comment]
Doesn't look like we will have this by Tuesday

**Comment by JoseRoman** [comment]
are these pdf's the same in the website?

**Comment by Ernie3** [comment]
No, this is something @theseanconn is creating himself that is specific to our school

**Comment by Ernie3** [comment]
We will be on the newsletter on the 24th, change of plans

**Comment by Ernie3** [comment]
Duplicate, #50
