### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#49]
I don't think it is corrected for Daylight Savings

**Comment by theseanconn** [comment]
And I just realized that I cant add labels or assign people or add milestones anymore @Ernie3

**Comment by Ernie3** [comment]
When is check-in? 10PM on Feb 26 2016?

**Comment by Ernie3** [comment]
http://www.wolframalpha.com/input/?i=116+days+18+minutes+from+now

**Comment by theseanconn** [comment]
The time it should be set to is 10:00 PM, February 26th, 2016

**Comment by Ernie3** [comment]
It is correct. JS is smarter than you think :)

**Comment by theseanconn** [comment]
Oh my bad

**Comment by Ernie3** [comment]
All good bro

On Mon, Nov 2, 2015 at 9:44 PM, Sean Connolly <notifications@github.com>
wrote:

> Oh my bad
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/49#issuecomment-153222396>
> .
>



-- 

Thank you,

Ernest G. Wilson III
Email: ErnestGWilsonIII@gmail.com
Cell: 302.668.7620
