### ISSUE TITLE
Add Twitter Integration

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#5]
Somewhere on the page (near the social section) there should be a Twitter integration to see recent tweets from @KHSMiniTHON (https://twitter.com/KHSMiniTHON)

**Comment by theseanconn** [comment]
Not sure what you need me to do? @JoseRoman

**Comment by Ernie3** [comment]
@theseanconn he wants you to test the twitter integration. Does the data on the website match the data on twitter.com? When you post something, does the website's twitter integration update?

**Comment by theseanconn** [comment]
Looks good!
