### ISSUE TITLE
Add all the email addresses to contact section

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#6]
Email from Sean C:

I am creating an email account for each committee.

They will be as follows (Not all created yet):

khsminithon@gmail.com ---- Overall Chairs

khsminithon.finance@gmail.com --- Finance Committee

khsminithon.communityoutreach@gmail.com --- Community Outreach

khsminithon.specialevents@gmail.com ---- Special Events

khsminithon.hospitality@gmail.com --- Hospitality

khsminithon.operations@gmail.com --- Operations

khsminithon.entertainment@gmail.com ---- Entertainment

khsminithon.socialmedia.tech@gmail.com --- Social Media/Tech

**Comment by theseanconn** [comment]
Fix the names in the selection box (Please make them exactly what I have below):
Overall
Finance
Community Outreach
Special Events
Hospitality
Operations
Entertainment
Social Media/Technology

**Comment by JoseRoman** [comment]
@theseanconn: Done  66c221ceec3a7f8ea4090147d63dc562156a181c

**Comment by theseanconn** [comment]
Thanks and okay.

**Comment by theseanconn** [comment]
You have two "Finances" with the second one saying "Finance Committee"

**Comment by JoseRoman** [comment]
@theseanconn: Fixed 8a4168048a9cea182862780a9c3942bdbb13a880

**Comment by theseanconn** [comment]
Thank you!

**Comment by Ernie3** [comment]
Social Media and Technology are now separate. Is this correct @theseanconn?

**Comment by theseanconn** [comment]
It is one email address, so no.
khsminithon.socialmedia.tech@gmail.com

On Tue, Oct 20, 2015 at 9:02 PM, Ernie Wilson <notifications@github.com>
wrote:

> Social Media and Technology are now separate. Is this correct @theseanconn
> <https://github.com/theseanconn>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/6#issuecomment-149749241>.
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

Event Page <http://fourdiamonds.donordrive.com/event/khs16>    Twitter
<http://twitter.com/khsminithon>  Instagram
<http://instagram.com/khsminithon>

**Comment by theseanconn** [comment]
But they could be two different selections that go to the same email if you want.

**Comment by Ernie3** [comment]
In all honesty I would prefer them to be, because if there is a problem on the website per say then that is independent of social media.

**Comment by theseanconn** [comment]
Okay. I am going to redo the emails
The social media email will just be
khsminithon.socialmedia@gmail.com
and technology will be
khsminithon.tech@gmail.com

On Tue, Oct 20, 2015 at 9:44 PM, Ernie Wilson <notifications@github.com>
wrote:

> In all honesty I would prefer them to be, because if there is a problem on
> the website per say then that is independent of social media.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/6#issuecomment-149754534>.
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

Event Page <http://fourdiamonds.donordrive.com/event/khs16>    Twitter
<http://twitter.com/khsminithon>  Instagram
<http://instagram.com/khsminithon>

**Comment by theseanconn** [comment]
Split the "Social Media/Tech into two separate

"Social Media" --- khsminithon.socialmedia@gmail.com

"Technology" --- khsminithon.tech@gmail.com
