### ISSUE TITLE
Important UI things to include in test

### ISSUE THREAD

**Issue by JoseRoman** [KHS-Minithon/website#7]
This should check for important UI stuff such as correct title, menu, logo, ect

**Comment by JoseRoman** [comment]
Permanent Things:
Title Should Always Be: Kennett High School Mini-THON (IN BIG FONT)
Underneath title: "Join us on February 26, 2016"
Underneath the underneath (above signup button): For the Fight. For The Cure. For The Kids.
Link to sing-up page
Committee Names and Email addresses
Instagram link
Twitter link
Facebook link (when we have it)
All of the links from the diamonds ("Mini-THONs" ; "Donations" ; "Raising Awareness" ; "Research") stay the same
The Donate Button link stays the same https://fourdiamonds.donordrive.com/index.cfm?fuseaction=donate.event&eventID=1179

The details and information in Issue #15 should go on the site and stay there.

**Comment by Ernie3** [comment]
We good here
