### ISSUE TITLE
Change Info

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/website#9]
Who Are We:
We are a group of KHS students dedicated to raise as much money as possible to fight pediatric cancer.

What We Do:
The KHSMini-THON raises money through fundraisers and our annual Mini-THON to benefit the Four Diamonds Fund (Link “Four Diamonds Fund” to http://fourdiamonds.org)

Why We Do It:
We do it for the fight. For the cure. For The Kids living with cancer.

Since When:
We have been fighting childhood cancer since 2015 with our first annual Mini-THON being held in February of 2016.

**Comment by Ernie3** [comment]
Cool, I'll make this change when I can

**Comment by theseanconn** [comment]
One more thing:
The title should be something like ( I am putting these in the order as they should appear, one under the other
Kennett High School Mini-THON
Come Join Us on February 26, 2016
For the Fight. For The Cure. For The Kids.
Then the signup link

**Comment by Ernie3** [comment]
Done

**Comment by theseanconn** [comment]
It hasnt been pushed to the website branch.
